@extends('layouts.app')

@php
    $featured = [
        ['title' => '潮汐之上', 'author' => '林渡', 'genre' => '都市 · 治愈', 'desc' => '她在每一次潮汐里寻找失散多年的答案，也终于学会与自己和解。', 'chapters' => 128, 'cover_a' => '#173f4a', 'cover_b' => '#d6a85b', 'slug' => 'chaoxi-zhi-shang'],
        ['title' => '长安有雪', 'author' => '白栩', 'genre' => '古言 · 权谋', 'desc' => '雪落长安时，旧日盟约和少年心事一同被重新翻开。', 'chapters' => 96, 'cover_a' => '#4c3148', 'cover_b' => '#d88979', 'slug' => 'changan-you-xue'],
        ['title' => '星河失物招领处', 'author' => '迟也', 'genre' => '科幻 · 群像', 'desc' => '在银河尽头经营一家小店，替旅人找回被遗忘的珍贵之物。', 'chapters' => 74, 'cover_a' => '#293760', 'cover_b' => '#e0bd7c', 'slug' => 'xinghe-shiwuzhaolingchu'],
    ];
    $newBooks = [
        ['title' => '春日失控', 'author' => '闻鹤', 'genre' => '青春 · 甜宠', 'chapters' => 31, 'cover_a' => '#995e4d', 'cover_b' => '#f1c8a7', 'slug' => 'chunri-shikong'],
        ['title' => '雾中来信', 'author' => '周折', 'genre' => '悬疑 · 现代', 'chapters' => 18, 'cover_a' => '#36444c', 'cover_b' => '#a8bfbd', 'slug' => 'wuzhong-laixin'],
        ['title' => '借一盏月光', 'author' => '南枝', 'genre' => '古言 · 轻喜', 'chapters' => 22, 'cover_a' => '#5c4b36', 'cover_b' => '#e6c88e', 'slug' => 'jie-yizhan-yueguang'],
        ['title' => '漫长的告白', 'author' => '顾栖迟', 'genre' => '言情 · 成长', 'chapters' => 27, 'cover_a' => '#6b3542', 'cover_b' => '#e6a6a4', 'slug' => 'manchang-de-gaobai'],
    ];
    $ranking = [
        ['title' => '借一盏月光', 'author' => '南枝', 'score' => '9.8', 'tag' => '古言', 'slug' => 'jie-yizhan-yueguang'],
        ['title' => '潮汐之上', 'author' => '林渡', 'score' => '9.7', 'tag' => '都市', 'slug' => 'chaoxi-zhi-shang'],
        ['title' => '无人区来客', 'author' => '季行舟', 'score' => '9.6', 'tag' => '科幻', 'slug' => 'wurenqu-laike'],
        ['title' => '春日失控', 'author' => '闻鹤', 'score' => '9.5', 'tag' => '青春', 'slug' => 'chunri-shikong'],
        ['title' => '长安有雪', 'author' => '白栩', 'score' => '9.4', 'tag' => '古言', 'slug' => 'changan-you-xue'],
    ];
@endphp

@section('title', __('ui.home.title'))
@section('content')
<main>
    <section class="hero-band"><div class="site-shell hero-grid"><div class="hero-copy"><p class="eyebrow"><span class="eyebrow-mark"></span> {{ __('ui.home.eyebrow') }}</p><h1>{{ __('ui.home.headline_before') }}<br><em>{{ __('ui.home.headline_after') }}</em></h1><p class="hero-lead">{{ __('ui.home.lead') }}</p><div class="hero-actions"><a class="button button-primary" href="{{ Route::has('novels.index') ? route('novels.index') : '#' }}">{{ __('ui.home.start_reading') }} <span aria-hidden="true">↗</span></a><a class="text-link" href="#featured">{{ __('ui.home.weekly_picks') }} <span aria-hidden="true">↓</span></a></div><div class="hero-meta" aria-label="{{ __('ui.home.stats_label') }}"><span><strong>{{ __('ui.home.works_metric', ['count' => '2,480']) }}</strong></span><span><strong>{{ __('ui.home.readers_metric') }}</strong></span><span><strong>{{ __('ui.home.daily_update') }}</strong></span></div></div><div class="hero-stage" aria-label="{{ __('ui.home.novel_preview') }}"><div class="stage-note stage-note-top">{{ __('ui.home.editors_note') }} <span>01</span></div><div class="stage-book stage-book-back"><span>长安<br>有雪</span></div><div class="stage-book stage-book-main"><span>潮汐<br>之上</span><small>{{ __('ui.components.author_credit', ['author' => '林渡']) }}</small></div><div class="stage-note stage-note-bottom"><span>{{ __('ui.home.editor_pick') }}</span> {{ __('ui.home.read_slowly') }}</div><div class="stage-line stage-line-one"></div><div class="stage-line stage-line-two"></div></div></div></section>
    <section id="featured" class="site-shell section-block"><div class="section-heading"><div><p class="eyebrow">{{ __('ui.home.featured_eyebrow') }}</p><h2>{{ __('ui.home.featured_title') }}</h2></div><a class="text-link" href="{{ Route::has('novels.index') ? route('novels.index') : '#' }}">{{ __('ui.home.all_featured') }} <span>→</span></a></div><div class="featured-grid">@foreach ($featured as $index => $book)<article class="featured-card {{ $index === 0 ? 'featured-card-primary' : '' }}"><a href="{{ Route::has('novels.show') ? route('novels.show', ['novel' => $book['slug']]) : '#' }}" class="cover-link"><x-book-cover :book="$book" size="large" /></a><div class="featured-card-copy"><p class="book-kicker">{{ $book['genre'] }}</p><h3><a href="{{ Route::has('novels.show') ? route('novels.show', ['novel' => $book['slug']]) : '#' }}">{{ $book['title'] }}</a></h3><p>{{ $book['desc'] }}</p><div class="book-byline"><span>{{ $book['author'] }}</span><span>{{ __('ui.home.updated_to', ['count' => $book['chapters']]) }}</span></div></div></article>@endforeach</div></section>
    <section class="site-shell section-block section-divider"><div class="section-heading"><div><p class="eyebrow">{{ __('ui.home.new_eyebrow') }}</p><h2>{{ __('ui.home.new_title') }}</h2></div><a class="text-link" href="{{ Route::has('novels.index') ? route('novels.index', ['sort' => 'new']) : '#' }}">{{ __('ui.home.discover_more') }} <span>→</span></a></div><div class="new-books-grid">@foreach ($newBooks as $book)<article class="book-row"><a href="{{ Route::has('novels.show') ? route('novels.show', ['novel' => $book['slug']]) : '#' }}"><x-book-cover :book="$book" size="small" /></a><div class="book-row-copy"><p class="book-kicker">{{ $book['genre'] }}</p><h3><a href="{{ Route::has('novels.show') ? route('novels.show', ['novel' => $book['slug']]) : '#' }}">{{ $book['title'] }}</a></h3><p class="muted">{{ $book['author'] }}</p><span class="chapter-count">{{ __('ui.home.updated_to', ['count' => $book['chapters']]) }}</span></div></article>@endforeach</div></section>
    <section class="rank-band"><div class="site-shell ranking-layout"><div class="rank-intro"><p class="eyebrow">{{ __('ui.home.ranking_eyebrow') }}</p><h2>{{ __('ui.home.ranking_title') }}<br><em>{{ __('ui.home.ranking_question') }}</em></h2><p>{{ __('ui.home.ranking_intro') }}</p><a class="button button-dark" href="{{ Route::has('novels.index') ? route('novels.index', ['sort' => 'hot']) : '#' }}">{{ __('ui.home.full_ranking') }} <span>→</span></a></div><div class="ranking-list">@foreach ($ranking as $index => $book)<a class="ranking-item" href="{{ Route::has('novels.show') ? route('novels.show', ['novel' => $book['slug']]) : '#' }}"><span class="rank-number">0{{ $index + 1 }}</span><span class="rank-title"><strong>{{ $book['title'] }}</strong><small>{{ $book['author'] }} · {{ $book['tag'] }}</small></span><span class="rank-score">{{ $book['score'] }}<small>{{ __('ui.home.score') }}</small></span></a>@endforeach</div></div></section>
    <section id="categories" class="site-shell category-strip"><p class="eyebrow">{{ __('ui.home.category_eyebrow') }}</p><div class="category-links"><a href="#">{{ __('ui.home.categories.urban') }} <span>238</span></a><a href="#">{{ __('ui.home.categories.ancient') }} <span>186</span></a><a href="#">{{ __('ui.home.categories.mystery') }} <span>92</span></a><a href="#">{{ __('ui.home.categories.scifi') }} <span>64</span></a><a href="#">{{ __('ui.home.categories.youth') }} <span>121</span></a></div></section>
</main>
@endsection
