<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = ['Meet stories here' => 'Bu ýerde hekaýalar bilen duşuşyň', 'Home' => 'Baş sahypa', 'Library' => 'Kitaphana', 'Categories' => 'Kategoriýalar', 'Search' => 'Gözle', 'Account' => 'Hasap', 'Log in' => 'Giriş', 'Log out' => 'Çykyş', 'Register' => 'Hasaba al', 'Admin' => 'Dolandyryş', 'Explore' => 'Gözden geçir', 'All works' => 'Ähli eserler', 'Choose language' => 'Dili saýlaň', 'Apply language' => 'Dili ulan', 'Light' => 'Açyk', 'Dark' => 'Garaňky', 'System' => 'Ulgam', 'Social' => 'Sosial bölüm', 'Private messages' => 'Şahsy habarlar', 'Reading groups' => 'Okuw toparlary', 'Submissions' => 'Teklipler', 'Hello, :name' => 'Salam, :name', 'Welcome back. Keep a little time for reading today.' => 'Täzeden hoş geldiňiz. Şu gün okamaga biraz wagt bölüň.', 'Search users' => 'Ulanyjylary gözle', 'Send message' => 'Habar iber', 'Create reading group' => 'Okuw toparyny döret', 'Create group' => 'Topar döret', 'Members' => 'Agzalar', 'Choose member' => 'Agzany saýla', 'Add member' => 'Agza goş', 'Email' => 'Elektron poçta', 'Password' => 'Parol', 'Remember me' => 'Meni ýatla', 'Forgot password?' => 'Parolyňyzy unutduňyzmy?', 'Create an account' => 'Hasap döret', 'Display name' => 'Görkezilýän at', 'Account type' => 'Hasap görnüşi', 'New password' => 'Täze parol', 'Reset password' => 'Paroly dikelt', 'My favorites' => 'Halanlarym', 'Reading history' => 'Okuw taryhy', 'Account settings' => 'Hasap sazlamalary', 'Save changes' => 'Üýtgetmeleri sakla', 'Start reading' => 'Okamaga başla', 'Continue' => 'Dowam et', 'Open' => 'Aç', 'Previous' => 'Öňki', 'Next' => 'Indiki', 'Contents' => 'Mazmun', 'Chapter list' => 'Baplaryň sanawy', 'Status' => 'Ýagdaý', 'Pending review' => 'Barlaga garaşýar', 'Approved' => 'Tassyklandy', 'Rejected' => 'Ret edildi', 'Draft' => 'Garalama', 'Published' => 'Çap edildi', 'Archived' => 'Arhiwlendi', 'Loading' => 'Ýüklenýär', 'Read' => 'Okaldy', 'Unread' => 'Okalmadyk', 'Me' => 'Men', 'Other' => 'Başga', 'No content' => 'Mazmun ýok', 'Anonymous user' => 'Näbelli ulanyjy', 'Anonymous author' => 'Näbelli awtor', 'Untitled work' => 'Ady ýok eser', 'Unknown' => 'Näbelli'];
$words = ['works' => 'eserler', 'readers' => 'okyjylar', 'story' => 'hekaýa', 'stories' => 'hekaýalar', 'chapter' => 'bap', 'chapters' => 'baplar', 'message' => 'habar', 'messages' => 'habarlar', 'group' => 'topar', 'groups' => 'toparlar', 'author' => 'awtor', 'reader' => 'okyjy', 'user' => 'ulanyjy', 'users' => 'ulanyjylar', 'name' => 'at', 'title' => 'ady', 'content' => 'mazmun', 'save' => 'sakla', 'saved' => 'saklandy', 'open' => 'aç', 'new' => 'täze', 'back' => 'yza', 'settings' => 'sazlamalar', 'review' => 'barlag', 'send' => 'iber', 'create' => 'döret', 'choose' => 'saýla', 'loading' => 'ýüklenýär', 'empty' => 'boş', 'today' => 'şu gün', 'recent' => 'soňky', 'email' => 'elektron poçta', 'password' => 'parol'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
