<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = [
    'Meet stories here' => 'Оқиғалармен осында қауышыңыз', 'Home' => 'Басты бет', 'Library' => 'Кітапхана', 'Categories' => 'Санаттар', 'Search' => 'Іздеу', 'Account' => 'Есептік жазба', 'Log in' => 'Кіру', 'Log out' => 'Шығу', 'Register' => 'Тіркелу', 'Admin' => 'Әкімшілік', 'Explore' => 'Зерттеу', 'All works' => 'Барлық шығармалар', 'Choose language' => 'Тілді таңдау', 'Apply language' => 'Тілді қолдану', 'Light' => 'Жарық', 'Dark' => 'Қараңғы', 'System' => 'Жүйе', 'Social' => 'Әлеуметтік бөлім', 'Private messages' => 'Жеке хабарламалар', 'Reading groups' => 'Оқу топтары', 'Submissions' => 'Жіберілімдер', 'Hello, :name' => 'Сәлем, :name', 'Welcome back. Keep a little time for reading today.' => 'Қайта қош келдіңіз. Бүгін оқуға аздап уақыт бөліңіз.', 'Search users' => 'Пайдаланушыларды іздеу', 'Send message' => 'Хабарлама жіберу', 'Create reading group' => 'Оқу тобын құру', 'Create group' => 'Топ құру', 'Members' => 'Мүшелер', 'Choose member' => 'Мүшені таңдау', 'Add member' => 'Мүше қосу', 'Email' => 'Электрондық пошта', 'Password' => 'Құпиясөз', 'Remember me' => 'Мені есте сақтау', 'Forgot password?' => 'Құпиясөзді ұмыттыңыз ба?', 'Create an account' => 'Есептік жазба ашу', 'Display name' => 'Көрсетілетін есім', 'Account type' => 'Есептік жазба түрі', 'New password' => 'Жаңа құпиясөз', 'Reset password' => 'Құпиясөзді қалпына келтіру', 'My favorites' => 'Таңдаулыларым', 'Reading history' => 'Оқу тарихы', 'Account settings' => 'Есептік жазба баптаулары', 'Save changes' => 'Өзгерістерді сақтау', 'Start reading' => 'Оқуды бастау', 'Continue' => 'Жалғастыру', 'Open' => 'Ашу', 'Previous' => 'Алдыңғы', 'Next' => 'Келесі', 'Contents' => 'Мазмұны', 'Chapter list' => 'Тараулар тізімі', 'Status' => 'Күйі', 'Pending review' => 'Тексеруді күтуде', 'Approved' => 'Мақұлданды', 'Rejected' => 'Қабылданбады', 'Draft' => 'Жоба', 'Published' => 'Жарияланды', 'Archived' => 'Мұрағатталды', 'Loading' => 'Жүктелуде', 'Read' => 'Оқылды', 'Unread' => 'Оқылмаған', 'Me' => 'Мен', 'Other' => 'Басқа', 'No content' => 'Мазмұн жоқ', 'Anonymous user' => 'Анонимді пайдаланушы', 'Anonymous author' => 'Анонимді автор', 'Untitled work' => 'Атаусыз шығарма', 'Unknown' => 'Белгісіз',
];
$words = ['works' => 'шығарма', 'readers' => 'оқырман', 'story' => 'оқиға', 'stories' => 'оқиғалар', 'chapter' => 'тарау', 'chapters' => 'тараулар', 'message' => 'хабарлама', 'messages' => 'хабарламалар', 'group' => 'топ', 'groups' => 'топтар', 'author' => 'автор', 'reader' => 'оқырман', 'user' => 'пайдаланушы', 'users' => 'пайдаланушылар', 'name' => 'атау', 'title' => 'тақырып', 'content' => 'мазмұн', 'save' => 'сақтау', 'saved' => 'сақталды', 'open' => 'ашу', 'new' => 'жаңа', 'back' => 'қайту', 'settings' => 'баптаулар', 'review' => 'тексеру', 'send' => 'жіберу', 'create' => 'құру', 'choose' => 'таңдау', 'loading' => 'жүктелуде', 'empty' => 'бос', 'today' => 'бүгін', 'recent' => 'соңғы', 'email' => 'электрондық пошта', 'password' => 'құпиясөз'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
