<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = ['Meet stories here' => 'Окуялар менен бул жерден таанышыңыз', 'Home' => 'Башкы бет', 'Library' => 'Китепкана', 'Categories' => 'Категориялар', 'Search' => 'Издөө', 'Account' => 'Каттоо эсеби', 'Log in' => 'Кирүү', 'Log out' => 'Чыгуу', 'Register' => 'Катталуу', 'Admin' => 'Башкаруу', 'Explore' => 'Изилдөө', 'All works' => 'Бардык чыгармалар', 'Choose language' => 'Тилди тандоо', 'Apply language' => 'Тилди колдонуу', 'Light' => 'Жарык', 'Dark' => 'Караңгы', 'System' => 'Система', 'Social' => 'Социалдык бөлүм', 'Private messages' => 'Жеке билдирүүлөр', 'Reading groups' => 'Окуу топтору', 'Submissions' => 'Сунуштар', 'Hello, :name' => 'Салам, :name', 'Welcome back. Keep a little time for reading today.' => 'Кайра кош келиңиз. Бүгүн окууга бир аз убакыт бөлүңүз.', 'Search users' => 'Колдонуучуларды издөө', 'Send message' => 'Билдирүү жөнөтүү', 'Create reading group' => 'Окуу тобун түзүү', 'Create group' => 'Топ түзүү', 'Members' => 'Мүчөлөр', 'Choose member' => 'Мүчөнү тандоо', 'Add member' => 'Мүчө кошуу', 'Email' => 'Электрондук почта', 'Password' => 'Сырсөз', 'Remember me' => 'Мени эстеп кал', 'Forgot password?' => 'Сырсөздү унуттуңузбу?', 'Create an account' => 'Эсеп түзүү', 'Display name' => 'Көрсөтүлүүчү ат', 'Account type' => 'Эсептин түрү', 'New password' => 'Жаңы сырсөз', 'Reset password' => 'Сырсөздү калыбына келтирүү', 'My favorites' => 'Тандалгандарым', 'Reading history' => 'Окуу тарыхы', 'Account settings' => 'Эсеп жөндөөлөрү', 'Save changes' => 'Өзгөртүүлөрдү сактоо', 'Start reading' => 'Окууну баштоо', 'Continue' => 'Улантуу', 'Open' => 'Ачуу', 'Previous' => 'Мурунку', 'Next' => 'Кийинки', 'Contents' => 'Мазмуну', 'Chapter list' => 'Бөлүмдөрдүн тизмеси', 'Status' => 'Абалы', 'Pending review' => 'Кароо күтүлүүдө', 'Approved' => 'Бекитилди', 'Rejected' => 'Четке кагылды', 'Draft' => 'Долбоор', 'Published' => 'Жарыяланды', 'Archived' => 'Архивделди', 'Loading' => 'Жүктөлүүдө', 'Read' => 'Окулду', 'Unread' => 'Окула элек', 'Me' => 'Мен', 'Other' => 'Башка', 'No content' => 'Мазмун жок', 'Anonymous user' => 'Белгисиз колдонуучу', 'Anonymous author' => 'Белгисиз автор', 'Untitled work' => 'Аталышы жок чыгарма', 'Unknown' => 'Белгисиз'];
$words = ['works' => 'чыгармалар', 'readers' => 'окурмандар', 'story' => 'окуя', 'stories' => 'окуялар', 'chapter' => 'бөлүм', 'chapters' => 'бөлүмдөр', 'message' => 'билдирүү', 'messages' => 'билдирүүлөр', 'group' => 'топ', 'groups' => 'топтор', 'author' => 'автор', 'reader' => 'окурман', 'user' => 'колдонуучу', 'users' => 'колдонуучулар', 'name' => 'ат', 'title' => 'аталыш', 'content' => 'мазмун', 'save' => 'сактоо', 'saved' => 'сакталды', 'open' => 'ачуу', 'new' => 'жаңы', 'back' => 'кайтуу', 'settings' => 'жөндөөлөр', 'review' => 'кароо', 'send' => 'жөнөтүү', 'create' => 'түзүү', 'choose' => 'тандоо', 'loading' => 'жүктөлүүдө', 'empty' => 'бош', 'today' => 'бүгүн', 'recent' => 'акыркы', 'email' => 'электрондук почта', 'password' => 'сырсөз'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
