<?php

$source = require __DIR__.'/../en/ui.php';
$map = [
    'Meet stories here' => 'Ontmoet stories hier', 'Skip to main content' => 'Spring na hoofinhoud', 'Choose language' => 'Kies taal', 'Apply language' => 'Pas taal toe',
    'Home' => 'Tuis', 'Library' => 'Biblioteek', 'Categories' => 'Kategorieë', 'Main navigation' => 'Hoofnavigasie', 'Mobile navigation' => 'Mobiele navigasie', 'Search novels' => 'Soek romans', 'Search works or authors' => 'Soek werke of outeurs', 'Search' => 'Soek', 'Account' => 'Rekening', 'Open account' => 'Open rekening', 'Admin' => 'Beheer', 'Log out' => 'Meld af', 'Log in' => 'Meld aan', 'Register' => 'Registreer', 'Open menu' => 'Open kieslys', 'Close menu' => 'Sluit kieslys', 'Explore' => 'Verken', 'All works' => 'Alle werke', 'Join us' => 'Sluit by ons aan', 'About Yuejing' => 'Oor Yuejing', 'Help' => 'Hulp', 'Reading guide' => 'Leesgids', 'Contact us' => 'Kontak ons', 'Light' => 'Lig', 'Dark' => 'Donker', 'Eye care' => 'Oogsorg', 'System' => 'Stelsel', 'Theme switcher' => 'Temawisselaar',
    'Account navigation' => 'Rekeningnavigasie', 'Reading overview' => 'Lees-oorsig', 'My favorites' => 'My gunstelinge', 'Reading history' => 'Leeskiedenis', 'Account settings' => 'Rekeninginstellings', 'Social' => 'Sosiaal', 'Private messages' => 'Privaat boodskappe', 'Reading groups' => 'Leesgroepe', 'Submissions' => 'Inhandigings',
    'My Yuejing' => 'My Yuejing', 'Hello, ' => 'Hallo, ', 'Welcome back.' => 'Welkom terug.', 'Discover stories' => 'Ontdek stories', 'Reading works' => 'Werke wat ek lees', 'Favorite works' => 'Gunstelingwerke', 'Submitted works' => 'Ingediende werke', 'Continue reading' => 'Gaan voort met lees', 'View all' => 'Wys alles', 'Continue' => 'Gaan voort', 'Work unavailable' => 'Werk nie beskikbaar nie', 'Browse library' => 'Blaai deur biblioteek', 'No reading history yet' => 'Nog geen leeskiedenis nie', 'Open' => 'Open', 'Your favorite works will appear here.' => 'Jou gunstelingwerke sal hier verskyn.', 'Communication' => 'Kommunikasie', 'Stay connected with readers and fellow writers' => 'Bly verbind met lesers en mede-outeurs', 'Start or continue a direct conversation' => 'Begin of gaan voort met ’n direkte gesprek', 'Open messages' => 'Open boodskappe', 'Join or create a reading group' => 'Sluit by ’n leesgroep aan of skep een', 'Open groups' => 'Open groepe', 'Pending review' => 'Wag op hersiening', 'Approved' => 'Goedgekeur', 'Needs changes' => 'Benodig wysigings',
    'Private messages' => 'Privaat boodskappe', 'Reading groups' => 'Leesgroepe', 'Search users' => 'Soek gebruikers', 'Search by name or email' => 'Soek volgens naam of e-pos', 'Loading' => 'Laai', 'Loading conversations' => 'Laai gesprekke', 'Loading groups' => 'Laai groepe', 'DIRECT CHAT' => 'DIREKTE GESPREK', 'GROUP CHAT' => 'GROEPGESPREK', 'Choose a conversation' => 'Kies ’n gesprek', 'Choose a group' => 'Kies ’n groep', 'Not connected' => 'Nie verbind nie', 'Send message' => 'Stuur boodskap', 'Create reading group' => 'Skep leesgroep', 'Group name' => 'Groepnaam', 'Choose members' => 'Kies lede', 'Create group' => 'Skep groep', 'Members' => 'Lede', 'Add member' => 'Voeg lid by', 'Choose member' => 'Kies lid',
    'Log in to Yuejing' => 'Meld by Yuejing aan', 'Email' => 'E-pos', 'Password' => 'Wagwoord', 'Remember me' => 'Onthou my', 'Forgot password?' => 'Wagwoord vergeet?', 'Create an account' => 'Skep ’n rekening', 'Display name' => 'Vertoonnaam', 'Account type' => 'Rekeningtipe', 'Reader: read, save, and sync progress' => 'Leser: lees, stoor en sinkroniseer vordering', 'Author: read and submit works' => 'Outeur: lees en dien werke in', 'Set password' => 'Stel wagwoord', 'Confirm password' => 'Bevestig wagwoord', 'Create account' => 'Skep rekening', 'Already have an account?' => 'Het jy reeds ’n rekening?', 'New password' => 'Nuwe wagwoord',
    'successful' => 'suksesvol', 'Welcome to Yuejing.' => 'Welkom by Yuejing.', 'Welcome back.' => 'Welkom terug.', 'invalid' => 'ongeldig', 'expired' => 'verval', 'enabled' => 'geaktiveer', 'disabled' => 'gedeaktiveer', 'Action completed.' => 'Aksie voltooi.', 'Settings updated.' => 'Instellings opgedateer.', 'Saved' => 'Gestoor', 'Save work' => 'Stoor werk', 'Chapters' => 'Hoofstukke', 'Status' => 'Status', 'Reader rating' => 'Lesergradering', 'Previous' => 'Vorige', 'Next' => 'Volgende', 'Contents' => 'Inhoud', 'Today' => 'Vandag', 'Word count' => 'Woordtelling', 'by' => 'deur', 'Anonymous author' => 'Anonieme outeur', 'Anonymous user' => 'Anonieme gebruiker', 'Untitled work' => 'Ongetitelde werk', 'No content' => 'Geen inhoud', 'Close notification' => 'Sluit kennisgewing', 'Current IP address' => 'Huidige IP-adres',
    'Draft' => 'Konsep', 'Published' => 'Gepubliseer', 'Archived' => 'Gearchiveer', 'Rejected' => 'Verwerp', 'In review' => 'Onder hersiening', 'Chapter' => 'Hoofstuk', 'Work title' => 'Werktitel', 'Genre' => 'Genre', 'Synopsis' => 'Sinopsis', 'Content' => 'Inhoud', 'Save changes' => 'Stoor wysigings', 'Edit' => 'Redigeer', 'Delete' => 'Verwyder', 'Save' => 'Stoor', 'Publish' => 'Publiseer', 'All' => 'Alles', 'Pending' => 'Wag', 'Author' => 'Outeur', 'Time' => 'Tyd', 'Target' => 'Teiken', 'Action' => 'Aksie', 'Operator' => 'Operateur', 'Metadata' => 'Metadata', 'No audit records yet.' => 'Nog geen ouditrekords nie.',
];
$fallback = 'Hierdie boodskap is beskikbaar.';
$keep = ['Yuejing', 'API', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', '2FA', 'IP', 'JSON'];
$translate = function ($value) use (&$translate, $map, $fallback, $keep) {
    if (is_array($value)) { foreach ($value as $key => $item) { $value[$key] = $translate($item); } return $value; }
    if (!is_string($value)) return $value;
    $result = strtr($value, $map);
    return $result;
};
return $translate($source);
