<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = ['Meet stories here' => 'Hikoyalar bilan shu yerda uchrashing', 'Home' => 'Bosh sahifa', 'Library' => 'Kutubxona', 'Categories' => 'Toifalar', 'Search' => 'Qidirish', 'Account' => 'Hisob', 'Log in' => 'Kirish', 'Log out' => 'Chiqish', 'Register' => 'Ro‘yxatdan o‘tish', 'Admin' => 'Boshqaruv', 'Explore' => 'Kashf etish', 'All works' => 'Barcha asarlar', 'Choose language' => 'Tilni tanlang', 'Apply language' => 'Tilni qo‘llash', 'Light' => 'Yorug‘', 'Dark' => 'Qorong‘i', 'System' => 'Tizim', 'Social' => 'Ijtimoiy bo‘lim', 'Private messages' => 'Shaxsiy xabarlar', 'Reading groups' => 'O‘qish guruhlari', 'Submissions' => 'Yuborilgan asarlar', 'Hello, :name' => 'Salom, :name', 'Welcome back. Keep a little time for reading today.' => 'Qaytganingizdan xursandmiz. Bugun o‘qishga biroz vaqt ajrating.', 'Search users' => 'Foydalanuvchilarni qidirish', 'Send message' => 'Xabar yuborish', 'Create reading group' => 'O‘qish guruhi yaratish', 'Create group' => 'Guruh yaratish', 'Members' => 'A’zolar', 'Choose member' => 'A’zoni tanlang', 'Add member' => 'A’zo qo‘shish', 'Email' => 'Elektron pochta', 'Password' => 'Parol', 'Remember me' => 'Meni eslab qolish', 'Forgot password?' => 'Parolni unutdingizmi?', 'Create an account' => 'Hisob yaratish', 'Display name' => 'Ko‘rsatiladigan ism', 'Account type' => 'Hisob turi', 'New password' => 'Yangi parol', 'Reset password' => 'Parolni tiklash', 'My favorites' => 'Sevimlilarim', 'Reading history' => 'O‘qish tarixi', 'Account settings' => 'Hisob sozlamalari', 'Save changes' => 'O‘zgarishlarni saqlash', 'Start reading' => 'O‘qishni boshlash', 'Continue' => 'Davom etish', 'Open' => 'Ochish', 'Previous' => 'Oldingi', 'Next' => 'Keyingi', 'Contents' => 'Mundarija', 'Chapter list' => 'Boblar ro‘yxati', 'Status' => 'Holat', 'Pending review' => 'Ko‘rib chiqilmoqda', 'Approved' => 'Tasdiqlangan', 'Rejected' => 'Rad etilgan', 'Draft' => 'Qoralama', 'Published' => 'Nashr qilingan', 'Archived' => 'Arxivlangan', 'Loading' => 'Yuklanmoqda', 'Read' => 'O‘qilgan', 'Unread' => 'O‘qilmagan', 'Me' => 'Men', 'Other' => 'Boshqa', 'No content' => 'Mazmun yo‘q', 'Anonymous user' => 'Noma’lum foydalanuvchi', 'Anonymous author' => 'Noma’lum muallif', 'Untitled work' => 'Nomsiz asar', 'Unknown' => 'Noma’lum'];
$words = ['works' => 'asarlar', 'readers' => 'o‘quvchilar', 'story' => 'hikoya', 'stories' => 'hikoyalar', 'chapter' => 'bob', 'chapters' => 'boblar', 'message' => 'xabar', 'messages' => 'xabarlar', 'group' => 'guruh', 'groups' => 'guruhlar', 'author' => 'muallif', 'reader' => 'o‘quvchi', 'user' => 'foydalanuvchi', 'users' => 'foydalanuvchilar', 'name' => 'nom', 'title' => 'sarlavha', 'content' => 'mazmun', 'save' => 'saqlash', 'saved' => 'saqlandi', 'open' => 'ochish', 'new' => 'yangi', 'back' => 'qaytish', 'settings' => 'sozlamalar', 'review' => 'ko‘rib chiqish', 'send' => 'yuborish', 'create' => 'yaratish', 'choose' => 'tanlash', 'loading' => 'yuklanmoqda', 'empty' => 'bo‘sh', 'today' => 'bugun', 'recent' => 'so‘nggi', 'email' => 'elektron pochta', 'password' => 'parol'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
