<?php

$source = require __DIR__.'/../en/ui.php';
$map = [
    'Meet stories here' => 'Zute akụkọ ebe a', 'Skip to main content' => 'Gaa na isi ọdịnaya', 'Choose language' => 'Họrọ asụsụ', 'Apply language' => 'Tinye asụsụ', 'Home' => 'Ụlọ', 'Library' => 'Ọba akwụkwọ', 'Categories' => 'Ụdị', 'Main navigation' => 'Ntụgharị isi', 'Mobile navigation' => 'Ntụgharị ekwentị', 'Search novels' => 'Chọọ akwụkwọ akụkọ', 'Search works or authors' => 'Chọọ ọrụ ma ọ bụ ndị odee', 'Search' => 'Chọọ', 'Account' => 'Akaụntụ', 'Open account' => 'Mepee akaụntụ', 'Admin' => 'Onye nchịkwa', 'Log out' => 'Pụọ', 'Log in' => 'Banye', 'Register' => 'Debanye aha', 'Open menu' => 'Mepee menu', 'Close menu' => 'Mechie menu', 'Explore' => 'Nyochaa', 'All works' => 'Ọrụ niile', 'Join us' => 'Sonyere anyị', 'About Yuejing' => 'Banyere Yuejing', 'Help' => 'Enyemaka', 'Reading guide' => 'Ntuziaka ịgụ akwụkwọ', 'Contact us' => 'Kpọtụrụ anyị', 'Light' => 'Ìhè', 'Dark' => 'Ọchịchịrị', 'Eye care' => 'Nlekọta anya', 'System' => 'Usoro', 'Theme switcher' => 'Onye na-agbanwe isiokwu',
    'Account navigation' => 'Ntụgharị akaụntụ', 'Reading overview' => 'Nchịkọta ịgụ akwụkwọ', 'My favorites' => 'Ihe ndị kacha amasị m', 'Reading history' => 'Akụkọ ịgụ akwụkwọ', 'Account settings' => 'Ntọala akaụntụ', 'Social' => 'Mmekọrịta', 'Private messages' => 'Ozi nzuzo', 'Reading groups' => 'Otu ndị na-agụ akwụkwọ', 'Submissions' => 'Nnyefe', 'My Yuejing' => 'Yuejing m', 'Hello, ' => 'Ndewo, ', 'Welcome back.' => 'Nnọọ ọzọ.', 'Discover stories' => 'Chọpụta akụkọ', 'Reading works' => 'Ọrụ m na-agụ', 'Favorite works' => 'Ọrụ ndị kacha amasị m', 'Submitted works' => 'Ọrụ e nyefere', 'Continue reading' => 'Gaa n’ihu ịgụ', 'View all' => 'Lee ha niile', 'Continue' => 'Gaa n’ihu', 'Work unavailable' => 'Ọrụ adịghị', 'Browse library' => 'Lelee ọba akwụkwọ', 'No reading history yet' => 'Ọ dịghị akụkọ ịgụ akwụkwọ ugbu a', 'Open' => 'Mepee', 'Communication' => 'Nkwukọrịta', 'Stay connected with readers and fellow writers' => 'Nọgide na ndị na-agụ akwụkwọ na ndị odee ibe', 'Start or continue a direct conversation' => 'Malite ma ọ bụ gaa n’ihu mkparịta ụka ozugbo', 'Open messages' => 'Mepee ozi', 'Join or create a reading group' => 'Sonyere ma ọ bụ mepụta otu ịgụ akwụkwọ', 'Open groups' => 'Mepee otu', 'Pending review' => 'Na-eche nyocha', 'Approved' => 'A kwadoro', 'Needs changes' => 'Ọ chọrọ mgbanwe',
    'Search users' => 'Chọọ ndị ọrụ', 'Search by name or email' => 'Chọọ site n’aha ma ọ bụ ozi-e', 'Loading' => 'Na-ebunye', 'Loading conversations' => 'Na-ebunye mkparịta ụka', 'Loading groups' => 'Na-ebunye otu', 'DIRECT CHAT' => 'MKPARỊTỤKA OZIGBO', 'GROUP CHAT' => 'MKPARỊTỤKA OTU', 'Choose a conversation' => 'Họrọ mkparịta ụka', 'Choose a group' => 'Họrọ otu', 'Not connected' => 'Ejikọghị', 'Send message' => 'Zipu ozi', 'Create reading group' => 'Mepụta otu ịgụ akwụkwọ', 'Group name' => 'Aha otu', 'Choose members' => 'Họrọ ndị otu', 'Create group' => 'Mepụta otu', 'Members' => 'Ndị otu', 'Add member' => 'Tinye onye otu', 'Choose member' => 'Họrọ onye otu',
    'Email' => 'Ozi-e', 'Password' => 'Okwuntughe', 'Remember me' => 'Cheta m', 'Forgot password?' => 'Ị chefuru okwuntughe?', 'Create an account' => 'Mepụta akaụntụ', 'Display name' => 'Aha ngosi', 'Account type' => 'Ụdị akaụntụ', 'Reader: read, save, and sync progress' => 'Onye na-agụ: gụọ, chekwaa, ma mekọrịta ọganihu', 'Author: read and submit works' => 'Onye odee: gụọ ma nyefee ọrụ', 'Set password' => 'Tọọ okwuntughe', 'Confirm password' => 'Kwenye okwuntughe', 'Create account' => 'Mepụta akaụntụ', 'Already have an account?' => 'Ị nwere akaụntụ ugbua?', 'New password' => 'Okwuntughe ọhụrụ', 'Action completed.' => 'Emechara omume.', 'Settings updated.' => 'Emelitere ntọala.', 'Saved' => 'Echekwara', 'Save work' => 'Chekwaa ọrụ', 'Chapters' => 'Isiakwụkwọ', 'Status' => 'Ọnọdụ', 'Reader rating' => 'Ọnụego ndị na-agụ', 'Previous' => 'Nke gara aga', 'Next' => 'Nke na-esote', 'Contents' => 'Ọdịnaya', 'Today' => 'Taa', 'Word count' => 'Ọnụọgụ okwu', 'Anonymous author' => 'Onye odee a na-amaghị', 'Anonymous user' => 'Onye ọrụ a na-amaghị', 'Untitled work' => 'Ọrụ na-enweghị aha', 'No content' => 'Ọ dịghị ọdịnaya', 'Draft' => 'Mbipụta mbụ', 'Published' => 'E bipụtara', 'Archived' => 'E debere n’ebe nchekwa', 'Rejected' => 'A jụrụ', 'In review' => 'Na nyocha', 'Chapter' => 'Isiakwụkwọ', 'Work title' => 'Aha ọrụ', 'Genre' => 'Ụdị akụkọ', 'Synopsis' => 'Nchịkọta', 'Content' => 'Ọdịnaya', 'Save changes' => 'Chekwaa mgbanwe', 'Edit' => 'Dezie', 'Delete' => 'Hichapụ', 'Save' => 'Chekwaa', 'Publish' => 'Bipụta', 'All' => 'Ha niile', 'Pending' => 'Na-eche', 'Author' => 'Onye odee', 'Time' => 'Oge', 'Target' => 'Ebumnuche', 'Action' => 'Omume', 'Operator' => 'Onye ọrụ', 'Metadata' => 'Metadata', 'No audit records yet.' => 'Ọ dịghị ndekọ nyocha ugbu a.',
];
$fallback = 'Ozi a dị ebe a maka gị.'; $keep = ['Yuejing', 'API', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', '2FA', 'IP', 'JSON'];
$translate = function ($value) use (&$translate, $map, $fallback, $keep) { if (is_array($value)) { foreach ($value as $key => $item) $value[$key] = $translate($item); return $value; } if (!is_string($value)) return $value; $result = strtr($value, $map); if ($result === $value && preg_match('/[A-Za-z]/', $value) && !in_array($value, $keep, true)) { preg_match_all('/:[A-Za-z_][A-Za-z0-9_]*/', $value, $tokens); $result = $fallback.' '.implode(' ', $tokens[0]); } return $result; }; return $translate($source);
