<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = ['Meet stories here' => 'Дар ин ҷо бо ҳикояҳо шинос шавед', 'Home' => 'Саҳифаи асосӣ', 'Library' => 'Китобхона', 'Categories' => 'Категорияҳо', 'Search' => 'Ҷустуҷӯ', 'Account' => 'Ҳисоб', 'Log in' => 'Ворид шудан', 'Log out' => 'Баромадан', 'Register' => 'Сабтином', 'Admin' => 'Идоракунӣ', 'Explore' => 'Кашф кардан', 'All works' => 'Ҳамаи асарҳо', 'Choose language' => 'Забонро интихоб кунед', 'Apply language' => 'Забонро татбиқ кунед', 'Light' => 'Рӯшан', 'Dark' => 'Торик', 'System' => 'Система', 'Social' => 'Бахши иҷтимоӣ', 'Private messages' => 'Паёмҳои хусусӣ', 'Reading groups' => 'Гурӯҳҳои мутолиа', 'Submissions' => 'Пешниҳодҳо', 'Hello, :name' => 'Салом, :name', 'Welcome back. Keep a little time for reading today.' => 'Хуш омадед. Имрӯз барои мутолиа каме вақт ҷудо кунед.', 'Search users' => 'Ҷустуҷӯи корбарон', 'Send message' => 'Фиристодани паём', 'Create reading group' => 'Эҷоди гурӯҳи мутолиа', 'Create group' => 'Эҷоди гурӯҳ', 'Members' => 'Аъзо', 'Choose member' => 'Аъзоро интихоб кунед', 'Add member' => 'Илова кардани аъзо', 'Email' => 'Почтаи электронӣ', 'Password' => 'Гузарвожа', 'Remember me' => 'Маро дар хотир нигоҳ дор', 'Forgot password?' => 'Гузарвожаро фаромӯш кардед?', 'Create an account' => 'Эҷоди ҳисоб', 'Display name' => 'Номи намоишӣ', 'Account type' => 'Навъи ҳисоб', 'New password' => 'Гузарвожаи нав', 'Reset password' => 'Барқарор кардани гузарвожа', 'My favorites' => 'Мунтахабҳои ман', 'Reading history' => 'Таърихи мутолиа', 'Account settings' => 'Танзимоти ҳисоб', 'Save changes' => 'Нигоҳ доштани тағйирот', 'Start reading' => 'Оғози мутолиа', 'Continue' => 'Идома додан', 'Open' => 'Кушодан', 'Previous' => 'Қаблӣ', 'Next' => 'Баъдӣ', 'Contents' => 'Мундариҷа', 'Chapter list' => 'Рӯйхати фаслҳо', 'Status' => 'Вазъият', 'Pending review' => 'Дар интизори баррасӣ', 'Approved' => 'Тасдиқшуда', 'Rejected' => 'Радшуда', 'Draft' => 'Лоиҳа', 'Published' => 'Нашршуда', 'Archived' => 'Бойгонӣ', 'Loading' => 'Бор шуда истодааст', 'Read' => 'Хонда шуд', 'Unread' => 'Хонда нашудааст', 'Me' => 'Ман', 'Other' => 'Дигар', 'No content' => 'Мундариҷа нест', 'Anonymous user' => 'Корбари беном', 'Anonymous author' => 'Муаллифи беном', 'Untitled work' => 'Асари беунвон', 'Unknown' => 'Номаълум'];
$words = ['works' => 'асарҳо', 'readers' => 'хонандагон', 'story' => 'ҳикоя', 'stories' => 'ҳикояҳо', 'chapter' => 'фасл', 'chapters' => 'фаслҳо', 'message' => 'паём', 'messages' => 'паёмҳо', 'group' => 'гурӯҳ', 'groups' => 'гурӯҳҳо', 'author' => 'муаллиф', 'reader' => 'хонанда', 'user' => 'корбар', 'users' => 'корбарон', 'name' => 'ном', 'title' => 'унвон', 'content' => 'мундариҷа', 'save' => 'нигоҳ доштан', 'saved' => 'нигоҳ дошта шуд', 'open' => 'кушодан', 'new' => 'нав', 'back' => 'бозгашт', 'settings' => 'танзимот', 'review' => 'баррасӣ', 'send' => 'фиристодан', 'create' => 'эҷод кардан', 'choose' => 'интихоб кардан', 'loading' => 'бор шуда истодааст', 'empty' => 'холӣ', 'today' => 'имрӯз', 'recent' => 'охирин', 'email' => 'почтаи электронӣ', 'password' => 'гузарвожа'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
