<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = ['Meet stories here' => 'دلته له کیسو سره ووینئ', 'Home' => 'کورپاڼه', 'Library' => 'کتابتون', 'Categories' => 'وېشنيزې', 'Search' => 'لټون', 'Account' => 'حساب', 'Log in' => 'ننوتل', 'Log out' => 'وتل', 'Register' => 'ثبت نام', 'Admin' => 'اداره', 'Explore' => 'کشف کول', 'All works' => 'ټول اثار', 'Choose language' => 'ژبه وټاکئ', 'Apply language' => 'ژبه پلي کړئ', 'Light' => 'روښانه', 'Dark' => 'تیاره', 'System' => 'سیسټم', 'Social' => 'ټولنیزه برخه', 'Private messages' => 'شخصي پیغامونه', 'Reading groups' => 'د لوستلو ډلې', 'Submissions' => 'سپارنې', 'Hello, :name' => 'سلام، :name', 'Welcome back. Keep a little time for reading today.' => 'بیا ښه راغلاست. نن د لوستلو لپاره لږ وخت ځانګړی کړئ.', 'Search users' => 'کاروونکي ولټوئ', 'Send message' => 'پیغام ولېږئ', 'Create reading group' => 'د لوستلو ډله جوړه کړئ', 'Create group' => 'ډله جوړه کړئ', 'Members' => 'غړي', 'Choose member' => 'غړی وټاکئ', 'Add member' => 'غړی زیات کړئ', 'Email' => 'برېښنالیک', 'Password' => 'پټ نوم', 'Remember me' => 'ما په یاد وساتئ', 'Forgot password?' => 'پټ نوم مو هېر کړی؟', 'Create an account' => 'حساب جوړ کړئ', 'Display name' => 'ښکاره نوم', 'Account type' => 'د حساب ډول', 'New password' => 'نوی پټ نوم', 'Reset password' => 'پټ نوم بیا وټاکئ', 'My favorites' => 'زما خوښې', 'Reading history' => 'د لوستلو تاریخ', 'Account settings' => 'د حساب امستنې', 'Save changes' => 'بدلونونه خوندي کړئ', 'Start reading' => 'لوستل پیل کړئ', 'Continue' => 'دوام ورکړئ', 'Open' => 'پرانیستل', 'Previous' => 'مخکینی', 'Next' => 'بل', 'Contents' => 'منځپانګه', 'Chapter list' => 'د څپرکو لېست', 'Status' => 'حالت', 'Pending review' => 'د کتنې په تمه', 'Approved' => 'منل شوی', 'Rejected' => 'رد شوی', 'Draft' => 'مسوده', 'Published' => 'خپور شوی', 'Archived' => 'زېرمه شوی', 'Loading' => 'پورته کېږي', 'Read' => 'لوستل شوی', 'Unread' => 'نه لوستل شوی', 'Me' => 'زه', 'Other' => 'بل', 'No content' => 'منځپانګه نشته', 'Anonymous user' => 'ناڅرګند کاروونکی', 'Anonymous author' => 'ناڅرګند لیکوال', 'Untitled work' => 'بې سرلیکه اثر', 'Unknown' => 'ناڅرګند'];
$words = ['works' => 'اثار', 'readers' => 'لوستونکي', 'story' => 'کیسه', 'stories' => 'کیسې', 'chapter' => 'څپرکی', 'chapters' => 'څپرکي', 'message' => 'پیغام', 'messages' => 'پیغامونه', 'group' => 'ډله', 'groups' => 'ډلې', 'author' => 'لیکوال', 'reader' => 'لوستونکی', 'user' => 'کاروونکی', 'users' => 'کاروونکي', 'name' => 'نوم', 'title' => 'سرلیک', 'content' => 'منځپانګه', 'save' => 'خوندي کول', 'saved' => 'خوندي شوی', 'open' => 'پرانیستل', 'new' => 'نوی', 'back' => 'بېرته', 'settings' => 'امستنې', 'review' => 'کتنه', 'send' => 'لېږل', 'create' => 'جوړول', 'choose' => 'ټاکل', 'loading' => 'پورته کېږي', 'empty' => 'تش', 'today' => 'نن', 'recent' => 'وروستی', 'email' => 'برېښنالیک', 'password' => 'پټ نوم'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
