<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = ['Meet stories here' => 'აქ შეხვდით საინტერესო ამბებს', 'Home' => 'მთავარი', 'Library' => 'ბიბლიოთეკა', 'Categories' => 'კატეგორიები', 'Search' => 'ძებნა', 'Account' => 'ანგარიში', 'Log in' => 'შესვლა', 'Log out' => 'გამოსვლა', 'Register' => 'რეგისტრაცია', 'Admin' => 'ადმინისტრირება', 'Explore' => 'აღმოაჩინე', 'All works' => 'ყველა ნაწარმოები', 'Choose language' => 'აირჩიეთ ენა', 'Apply language' => 'ენის გამოყენება', 'Light' => 'ნათელი', 'Dark' => 'მუქი', 'System' => 'სისტემური', 'Social' => 'სოციალური', 'Private messages' => 'პირადი შეტყობინებები', 'Reading groups' => 'კითხვის ჯგუფები', 'Submissions' => 'ნამუშევრების გაგზავნა', 'Hello, :name' => 'გამარჯობა, :name', 'Welcome back. Keep a little time for reading today.' => 'კეთილი იყოს თქვენი დაბრუნება. დღეს ცოტაოდენი დრო დაუთმეთ კითხვას.', 'Search users' => 'მომხმარებლების ძებნა', 'Send message' => 'შეტყობინების გაგზავნა', 'Create reading group' => 'კითხვის ჯგუფის შექმნა', 'Create group' => 'ჯგუფის შექმნა', 'Members' => 'წევრები', 'Choose member' => 'აირჩიეთ წევრი', 'Add member' => 'წევრის დამატება', 'Email' => 'ელფოსტა', 'Password' => 'პაროლი', 'Remember me' => 'დამიმახსოვრე', 'Forgot password?' => 'დაგავიწყდათ პაროლი?', 'Create an account' => 'ანგარიშის შექმნა', 'Display name' => 'საჩვენებელი სახელი', 'Account type' => 'ანგარიშის ტიპი', 'New password' => 'ახალი პაროლი', 'Reset password' => 'პაროლის აღდგენა', 'My favorites' => 'ჩემი რჩეულები', 'Reading history' => 'კითხვის ისტორია', 'Account settings' => 'ანგარიშის პარამეტრები', 'Save changes' => 'ცვლილებების შენახვა', 'Start reading' => 'კითხვის დაწყება', 'Continue' => 'გაგრძელება', 'Open' => 'გახსნა', 'Previous' => 'წინა', 'Next' => 'შემდეგი', 'Contents' => 'სარჩევი', 'Chapter list' => 'თავების სია', 'Status' => 'სტატუსი', 'Pending review' => 'განხილვის მოლოდინში', 'Approved' => 'დადასტურებულია', 'Rejected' => 'უარყოფილია', 'Draft' => 'შავი მონახაზი', 'Published' => 'გამოქვეყნებულია', 'Archived' => 'არქივშია', 'Loading' => 'იტვირთება', 'Read' => 'წაკითხული', 'Unread' => 'წაუკითხავი', 'Me' => 'მე', 'Other' => 'სხვა', 'No content' => 'შინაარსი არ არის', 'Anonymous user' => 'ანონიმური მომხმარებელი', 'Anonymous author' => 'ანონიმური ავტორი', 'Untitled work' => 'უსათაურო ნაწარმოები', 'Unknown' => 'უცნობი'];
$words = ['works' => 'ნაწარმოებები', 'readers' => 'მკითხველები', 'story' => 'ამბავი', 'stories' => 'ამბები', 'chapter' => 'თავი', 'chapters' => 'თავები', 'message' => 'შეტყობინება', 'messages' => 'შეტყობინებები', 'group' => 'ჯგუფი', 'groups' => 'ჯგუფები', 'author' => 'ავტორი', 'reader' => 'მკითხველი', 'user' => 'მომხმარებელი', 'users' => 'მომხმარებლები', 'name' => 'სახელი', 'title' => 'სათაური', 'content' => 'შინაარსი', 'save' => 'შენახვა', 'saved' => 'შენახულია', 'open' => 'გახსნა', 'new' => 'ახალი', 'back' => 'უკან', 'settings' => 'პარამეტრები', 'review' => 'განხილვა', 'send' => 'გაგზავნა', 'create' => 'შექმნა', 'choose' => 'არჩევა', 'loading' => 'იტვირთება', 'empty' => 'ცარიელი', 'today' => 'დღეს', 'recent' => 'ბოლო', 'email' => 'ელფოსტა', 'password' => 'პაროლი'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
