<?php

$source = require __DIR__.'/../en/ui.php';
$map = [
    'Meet stories here' => 'Haɗu da labarai a nan', 'Skip to main content' => 'Tsallaka zuwa babban abun ciki', 'Choose language' => 'Zaɓi harshe', 'Apply language' => 'Aiwatar da harshe', 'Home' => 'Gida', 'Library' => 'Dakin karatu', 'Categories' => 'Rukuni', 'Main navigation' => 'Kewayawa ta farko', 'Mobile navigation' => 'Kewayawar waya', 'Search novels' => 'Nemo littattafai', 'Search works or authors' => 'Nemo ayyuka ko marubuta', 'Search' => 'Nema', 'Account' => 'Asusu', 'Open account' => 'Buɗe asusu', 'Admin' => 'Mai gudanarwa', 'Log out' => 'Fita', 'Log in' => 'Shiga', 'Register' => 'Yi rajista', 'Open menu' => 'Buɗe menu', 'Close menu' => 'Rufe menu', 'Explore' => 'Bincika', 'All works' => 'Dukan ayyuka', 'Join us' => 'Shiga tare da mu', 'About Yuejing' => 'Game da Yuejing', 'Help' => 'Taimako', 'Reading guide' => 'Jagorar karatu', 'Contact us' => 'Tuntube mu', 'Light' => 'Haske', 'Dark' => 'Duhu', 'Eye care' => 'Kula da ido', 'System' => 'Tsari', 'Theme switcher' => 'Mai canza jigo',
    'Account navigation' => 'Kewayawar asusu', 'Reading overview' => 'Taƙaitaccen karatu', 'My favorites' => 'Abubuwan da na fi so', 'Reading history' => 'Tarihin karatu', 'Account settings' => 'Saitunan asusu', 'Social' => 'Sadarwa', 'Private messages' => 'Saƙonnin sirri', 'Reading groups' => 'Ƙungiyoyin karatu', 'Submissions' => 'Ayyukan da aka tura', 'My Yuejing' => 'Yuejing na', 'Hello, ' => 'Sannu, ', 'Welcome back.' => 'Barka da dawowa.', 'Discover stories' => 'Gano labarai', 'Reading works' => 'Ayyukan da nake karantawa', 'Favorite works' => 'Ayyukan da na fi so', 'Submitted works' => 'Ayyukan da aka tura', 'Continue reading' => 'Ci gaba da karatu', 'View all' => 'Duba duka', 'Continue' => 'Ci gaba', 'Work unavailable' => 'Ba a samun aikin', 'Browse library' => 'Duba dakin karatu', 'No reading history yet' => 'Babu tarihin karatu tukuna', 'Open' => 'Buɗe', 'Communication' => 'Sadarwa', 'Stay connected with readers and fellow writers' => 'Kasance kusa da masu karatu da marubuta abokai', 'Start or continue a direct conversation' => 'Fara ko ci gaba da tattaunawa kai tsaye', 'Open messages' => 'Buɗe saƙonni', 'Join or create a reading group' => 'Shiga ko ƙirƙiri ƙungiyar karatu', 'Open groups' => 'Buɗe ƙungiyoyi', 'Pending review' => 'Ana jiran dubawa', 'Approved' => 'An amince', 'Needs changes' => 'Yana buƙatar gyara',
    'Search users' => 'Nemo masu amfani', 'Search by name or email' => 'Nema da suna ko imel', 'Loading' => 'Ana lodawa', 'Loading conversations' => 'Ana lodin tattaunawa', 'Loading groups' => 'Ana lodin ƙungiyoyi', 'DIRECT CHAT' => 'TATTAUNAWA KAI TSAYE', 'GROUP CHAT' => 'TATTAUNAWAR ƘUNGIYA', 'Choose a conversation' => 'Zaɓi tattaunawa', 'Choose a group' => 'Zaɓi ƙungiya', 'Not connected' => 'Ba a haɗa ba', 'Send message' => 'Aika saƙo', 'Create reading group' => 'Ƙirƙiri ƙungiyar karatu', 'Group name' => 'Sunan ƙungiya', 'Choose members' => 'Zaɓi mambobi', 'Create group' => 'Ƙirƙiri ƙungiya', 'Members' => 'Mambobi', 'Add member' => 'Ƙara mamba', 'Choose member' => 'Zaɓi mamba',
    'Email' => 'Imel', 'Password' => 'Kalmar sirri', 'Remember me' => 'Ka tuna da ni', 'Forgot password?' => 'Ka manta kalmar sirri?', 'Create an account' => 'Ƙirƙiri asusu', 'Display name' => 'Sunan nunawa', 'Account type' => 'Nau’in asusu', 'Reader: read, save, and sync progress' => 'Mai karatu: karanta, adana, kuma daidaita ci gaba', 'Author: read and submit works' => 'Marubuci: karanta kuma tura ayyuka', 'Set password' => 'Saita kalmar sirri', 'Confirm password' => 'Tabbatar da kalmar sirri', 'Create account' => 'Ƙirƙiri asusu', 'Already have an account?' => 'Kana da asusu tuni?', 'New password' => 'Sabuwar kalmar sirri', 'Action completed.' => 'An kammala aiki.', 'Settings updated.' => 'An sabunta saituna.', 'Saved' => 'An adana', 'Save work' => 'Adana aiki', 'Chapters' => 'Babi', 'Status' => 'Matsayi', 'Reader rating' => 'Ra’ayin masu karatu', 'Previous' => 'Na baya', 'Next' => 'Na gaba', 'Contents' => 'Abubuwan ciki', 'Today' => 'Yau', 'Word count' => 'Yawan kalmomi', 'Anonymous author' => 'Marubucin da ba a sani ba', 'Anonymous user' => 'Mai amfani da ba a sani ba', 'Untitled work' => 'Aiki marar suna', 'No content' => 'Babu abun ciki', 'Draft' => 'Daftari', 'Published' => 'An wallafa', 'Archived' => 'An adana a rumbun ajiya', 'Rejected' => 'An ƙi', 'In review' => 'Ana dubawa', 'Chapter' => 'Babi', 'Work title' => 'Sunan aiki', 'Genre' => 'Nau’i', 'Synopsis' => 'Taƙaitaccen bayani', 'Content' => 'Abun ciki', 'Save changes' => 'Ajiye sauye-sauye', 'Edit' => 'Gyara', 'Delete' => 'Goge', 'Save' => 'Ajiye', 'Publish' => 'Wallafa', 'All' => 'Duka', 'Pending' => 'Ana jira', 'Author' => 'Marubuci', 'Time' => 'Lokaci', 'Target' => 'Manufa', 'Action' => 'Aiki', 'Operator' => 'Mai aiki', 'Metadata' => 'Bayanan metadata', 'No audit records yet.' => 'Babu bayanan duba tukuna.',
];
$fallback = 'Wannan saƙon yana nan.'; $keep = ['Yuejing', 'API', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', '2FA', 'IP', 'JSON'];
$translate = function ($value) use (&$translate, $map, $fallback, $keep) { if (is_array($value)) { foreach ($value as $key => $item) $value[$key] = $translate($item); return $value; } if (!is_string($value)) return $value; $result = strtr($value, $map); if ($result === $value && preg_match('/[A-Za-z]/', $value) && !in_array($value, $keep, true)) { preg_match_all('/:[A-Za-z_][A-Za-z0-9_]*/', $value, $tokens); $result = $fallback.' '.implode(' ', $tokens[0]); } return $result; };
return $translate($source);
