@extends('layouts.app')

@php
    $book = isset($novel) ? (is_array($novel) ? $novel : ['title' => data_get($novel, 'title', '潮汐之上'), 'author' => data_get($novel, 'author', '林渡')]) : ['title' => '潮汐之上', 'author' => '林渡'];
    $chapter = isset($chapter) ? (is_array($chapter) ? $chapter : ['number' => data_get($chapter, 'number', 1), 'title' => data_get($chapter, 'title', '潮声从远处来'), 'content' => data_get($chapter, 'content', '')]) : ['number' => 1, 'title' => '潮声从远处来', 'content' => ''];
    $paragraphs = !empty($chapter['content']) ? preg_split('/\r\n|\r|\n/', strip_tags($chapter['content'])) : ['海风从旧码头的另一端吹来，带着潮湿的盐味。林知遥站在灯塔下，看见天边最后一线晚霞慢慢沉入海面。','她手里攥着那封没有署名的信，纸角已经被反复折叠，留下细密的纹路。信上只有一句话：如果你还记得那片海，就回来。','她当然记得。那是她离开故乡的第一个夏天，也是后来每一次想起青春时，最先浮现的声音。潮水拍打堤岸，一下一下，像有人在远处耐心地敲门。','“你终于来了。”身后有人说。她回过头，看见旧书店的门半掩着，门缝里亮着一盏暖黄色的灯。','那一刻，她忽然明白，有些故事并不会真正结束。它们只是暂时退潮，等一个愿意重新走近的人。'];
@endphp
@section('title', $book['title'].' · '.__('ui.reader.title_separator', ['number' => $chapter['number'] ?? 1]))
@section('content')
<main class="reader-shell"><header class="reader-header"><div class="site-shell reader-nav"><a class="reader-book" href="{{ Route::has('novels.show') ? route('novels.show', ['novel' => $book['slug'] ?? 'demo']) : '#' }}"><span>‹ {{ __('ui.reader.back_to_work') }}</span><small>{{ $book['title'] }} · {{ $book['author'] ?? __('ui.library.anonymous_author') }}</small></a><div class="reader-controls" aria-label="{{ __('ui.reader.settings_label') }}"><button type="button" data-reader-size="decrease" aria-label="{{ __('ui.reader.decrease_font') }}" aria-disabled="false">A−</button><button class="reader-size" type="button" data-reader-theme aria-pressed="false" aria-label="{{ __('ui.reader.toggle_night') }}">{{ __('ui.reader.settings_label') }}</button><button type="button" data-reader-size="increase" aria-label="{{ __('ui.reader.increase_font') }}" aria-disabled="false">A＋</button></div></div></header><p class="sr-only" data-reader-status aria-live="polite"></p><article class="reader-main"><p class="reader-kicker">{{ $book['title'] }} · {{ __('ui.reader.chapter_prefix', ['number' => $chapter['number'] ?? 1]) }}</p><h1>{{ $chapter['title'] ?? __('ui.reader.default_title') }}</h1><div class="reader-copy markdown-preview" data-reader-copy data-font-size="18">@if (!empty($chapter['content_html'])){!! $chapter['content_html'] !!}@else @foreach ($paragraphs as $paragraph)<p>{{ trim($paragraph) }}</p>@endforeach @endif</div><nav class="reader-footer" aria-label="{{ __('ui.reader.chapter_navigation') }}"><a href="{{ Route::has('novels.read') ? route('novels.read', ['novel' => $book['slug'] ?? 'demo', 'chapter' => max(1, (int) ($chapter['number'] ?? 1) - 1)]) : '#' }}">← {{ __('ui.reader.previous') }}</a><a href="{{ Route::has('novels.show') ? route('novels.show', ['novel' => $book['slug'] ?? 'demo']) : '#' }}">{{ __('ui.reader.directory') }}</a><a href="{{ Route::has('novels.read') ? route('novels.read', ['novel' => $book['slug'] ?? 'demo', 'chapter' => (int) ($chapter['number'] ?? 1) + 1]) : '#' }}">{{ __('ui.reader.next') }} →</a></nav></article></main>
@endsection
