@extends('layouts.app')

@php
    $fallback = ['title' => '潮汐之上', 'author' => '林渡', 'genre' => '都市 · 治愈', 'desc' => '她在每一次潮汐里寻找失散多年的答案，也终于学会与自己和解。海风吹过旧码头，新的生活从一封没有署名的信开始。', 'chapters' => 128, 'status' => __('ui.library.ongoing'), 'cover_a' => '#173f4a', 'cover_b' => '#d6a85b', 'slug' => 'chaoxi-zhi-shang'];
    $book = isset($novel) ? (is_array($novel) ? array_merge($fallback, $novel) : array_merge($fallback, ['title' => data_get($novel, 'title', $fallback['title']), 'author' => data_get($novel, 'author', $fallback['author']), 'desc' => data_get($novel, 'description', $fallback['desc']), 'chapters' => data_get($novel, 'chapters_count', $fallback['chapters'])])) : $fallback;
    $isFavorited = $isFavorited ?? false;
    $chapters = isset($chapters) && is_iterable($chapters) && count($chapters) ? $chapters : collect(range(1, 12))->map(fn ($n) => ['number' => $n, 'title' => ['潮声从远处来', '一封没有署名的信', '沿着旧地图出发', '雨停在黄昏之前', '她说起那年夏天', '海面上的微光', '我们终于重逢', '一场温柔的告别', '把秘密交给风', '在潮汐抵达之前', '新的地址', '故事仍在继续'][$n - 1], 'date' => $n === 12 ? __('ui.novel_detail.today') : '06-'.str_pad((string) (20 - $n), 2, '0', STR_PAD_LEFT)])->all();
@endphp

@section('title', $book['title'].' · '.__('ui.novel_detail.title_suffix'))
@section('content')
<main>
    <section class="detail-band"><div class="site-shell detail-grid"><div class="detail-cover"><x-book-cover :book="$book" size="large" /></div><div class="detail-copy"><p class="eyebrow">{{ $book['genre'] ?? __('ui.novel_detail.default_genre') }}</p><h1>{{ $book['title'] }}</h1><p class="detail-author">{{ $book['author'] ?? __('ui.novel_detail.anonymous_author') }} {{ __('ui.novel_detail.author_suffix') }}</p><p class="detail-desc">{{ $book['desc'] ?? $book['description'] ?? __('ui.novel_detail.default_description') }}</p><div class="detail-actions"><a class="button button-primary" href="{{ Route::has('novels.read') ? route('novels.read', ['novel' => $book['slug'] ?? 'demo', 'chapter' => 1]) : '#' }}">{{ __('ui.novel_detail.start_reading') }} <span>↗</span></a>@auth<form method="POST" action="{{ $isFavorited ? route('novels.unfavorite', $book['slug']) : route('novels.favorite', $book['slug']) }}">@csrf @if ($isFavorited) @method('DELETE') @endif<button class="button button-outline" type="submit">{{ $isFavorited ? __('ui.novel_detail.favorited') : __('ui.novel_detail.favorite') }}</button></form>@else<a class="button button-outline" href="{{ route('login.page') }}">{{ __('ui.novel_detail.favorite') }}</a>@endauth</div><div class="detail-stats"><span><strong>{{ $book['chapters'] ?? 0 }}</strong>{{ __('ui.novel_detail.chapters') }}</span><span><strong>{{ $book['status'] ?? __('ui.library.ongoing') }}</strong>{{ __('ui.novel_detail.status') }}</span><span><strong>9.7</strong>{{ __('ui.novel_detail.rating') }}</span></div></div></div></section>
    <section class="site-shell page-content"><div class="chapter-layout"><div><div class="section-heading"><div><p class="eyebrow">{{ __('ui.novel_detail.chapter_eyebrow') }}</p><h2>{{ __('ui.novel_detail.chapter_list') }}</h2></div><span class="muted">{{ __('ui.novel_detail.chapter_total', ['count' => count($chapters)]) }}</span></div><div class="chapter-list">@foreach ($chapters as $chapter)<a class="chapter-item" href="{{ Route::has('novels.read') ? route('novels.read', ['novel' => $book['slug'] ?? 'demo', 'chapter' => data_get($chapter, 'number', $loop->iteration)]) : '#' }}"><span>{{ __('ui.novel_detail.chapter_prefix', ['number' => data_get($chapter, 'number', $loop->iteration)]) }}　{{ data_get($chapter, 'title', __('ui.novel_detail.unnamed_chapter')) }}</span><small>{{ data_get($chapter, 'date', __('ui.novel_detail.pending_update')) }}</small></a>@endforeach</div></div><aside class="detail-aside"><h3>{{ __('ui.novel_detail.info') }}</h3><div class="aside-row"><span>{{ __('ui.novel_detail.type') }}</span><strong>{{ $book['genre'] ?? __('ui.library.untitled') }}</strong></div><div class="aside-row"><span>{{ __('ui.novel_detail.last_updated') }}</span><strong>{{ __('ui.novel_detail.today') }}</strong></div><div class="aside-row"><span>{{ __('ui.novel_detail.word_count') }}</span><strong>{{ __('ui.novel_detail.word_count_metric', ['count' => '32.8']) }}</strong></div><div class="aside-row"><span>{{ __('ui.novel_detail.collection_count') }}</span><strong>8,642</strong></div></aside></div></section>
</main>
@endsection
