@extends('layouts.app')

@php
    $fallback = ['title' => '潮汐之上', 'author' => '林渡', 'genre' => '都市 · 治愈', 'desc' => '她在每一次潮汐里寻找失散多年的答案，也终于学会与自己和解。海风吹过旧码头，新的生活从一封没有署名的信开始。', 'chapters' => 128, 'status' => '连载中', 'cover_a' => '#173f4a', 'cover_b' => '#d6a85b', 'slug' => 'chaoxi-zhi-shang'];
    $book = isset($novel) ? (is_array($novel) ? array_merge($fallback, $novel) : array_merge($fallback, ['title' => data_get($novel, 'title', $fallback['title']), 'author' => data_get($novel, 'author', $fallback['author']), 'desc' => data_get($novel, 'description', $fallback['desc']), 'chapters' => data_get($novel, 'chapters_count', $fallback['chapters'])])) : $fallback;
    $chapters = isset($chapters) && is_iterable($chapters) && count($chapters) ? $chapters : collect(range(1, 12))->map(fn ($n) => ['number' => $n, 'title' => ['潮声从远处来', '一封没有署名的信', '沿着旧地图出发', '雨停在黄昏之前', '她说起那年夏天', '海面上的微光', '我们终于重逢', '一场温柔的告别', '把秘密交给风', '在潮汐抵达之前', '新的地址', '故事仍在继续'][$n - 1], 'date' => $n === 12 ? '刚刚' : '06-'.str_pad((string) (20 - $n), 2, '0', STR_PAD_LEFT)])->all();
@endphp

@section('title', $book['title'].' · 阅境')
@section('content')
<main>
    <section class="detail-band"><div class="site-shell detail-grid"><div class="detail-cover">@include('partials.book-cover', ['book' => $book, 'size' => 'large'])</div><div class="detail-copy"><p class="eyebrow">{{ $book['genre'] ?? '现代 · 故事' }}</p><h1>{{ $book['title'] }}</h1><p class="detail-author">{{ $book['author'] ?? '匿名作者' }} 著</p><p class="detail-desc">{{ $book['desc'] ?? $book['description'] ?? '作者还没有留下简介，但故事已经准备好被打开。' }}</p><div class="detail-actions"><a class="button button-primary" href="{{ Route::has('novels.read') ? route('novels.read', ['novel' => $book['slug'] ?? 'demo', 'chapter' => 1]) : '#' }}">开始阅读 <span>↗</span></a><button class="button button-outline" type="button">♡ 收藏作品</button></div><div class="detail-stats"><span><strong>{{ $book['chapters'] ?? 0 }}</strong>章节</span><span><strong>{{ $book['status'] ?? '连载中' }}</strong>状态</span><span><strong>9.7</strong>读者评分</span></div></div></div></section>
    <section class="site-shell page-content"><div class="chapter-layout"><div><div class="section-heading"><div><p class="eyebrow">CHAPTERS</p><h2>章节目录</h2></div><span class="muted">共 {{ count($chapters) }} 章 · 持续更新中</span></div><div class="chapter-list">@foreach ($chapters as $chapter)<a class="chapter-item" href="{{ Route::has('novels.read') ? route('novels.read', ['novel' => $book['slug'] ?? 'demo', 'chapter' => data_get($chapter, 'number', $loop->iteration)]) : '#' }}"><span>第 {{ data_get($chapter, 'number', $loop->iteration) }} 章　{{ data_get($chapter, 'title', '未命名章节') }}</span><small>{{ data_get($chapter, 'date', '待更新') }}</small></a>@endforeach</div></div><aside class="detail-aside"><h3>作品信息</h3><div class="aside-row"><span>作品类型</span><strong>{{ $book['genre'] ?? '小说' }}</strong></div><div class="aside-row"><span>最后更新</span><strong>今日</strong></div><div class="aside-row"><span>字数</span><strong>32.8 万字</strong></div><div class="aside-row"><span>收藏人数</span><strong>8,642</strong></div></aside></div></section>
</main>
@endsection