<?php

$source = require __DIR__.'/../en/ui.php';
$map = [
    'Meet stories here' => 'Pade awon itan nibi', 'Skip to main content' => 'Fo si akoonu pataki', 'Choose language' => 'Yan ede', 'Apply language' => 'Lo ede', 'Home' => 'Ile', 'Library' => 'Ibi ikawe', 'Categories' => 'Awon isori', 'Main navigation' => 'Irinajo pataki', 'Mobile navigation' => 'Irinajo alagbeka', 'Search novels' => 'Wa awon iwe itan', 'Search works or authors' => 'Wa awon ise tabi awon onkowe', 'Search' => 'Wa', 'Account' => 'Akọọlẹ', 'Open account' => 'Ṣii akọọlẹ', 'Admin' => 'Alakoso', 'Log out' => 'Jade', 'Log in' => 'Wọle', 'Register' => 'Forukọsilẹ', 'Open menu' => 'Ṣii akojọ', 'Close menu' => 'Pa akojọ', 'Explore' => 'Ṣawari', 'All works' => 'Gbogbo awon ise', 'Join us' => 'Darapo mo wa', 'About Yuejing' => 'Nipa Yuejing', 'Help' => 'Iranwo', 'Reading guide' => 'Itọsọna kika', 'Contact us' => 'Kan si wa', 'Light' => 'Imole', 'Dark' => 'Okunkun', 'Eye care' => 'Itoju oju', 'System' => 'Eto', 'Theme switcher' => 'Ayipada akori',
    'Account navigation' => 'Irinajo akọọlẹ', 'Reading overview' => 'Akopọ kika', 'My favorites' => 'Awon ayanfẹ mi', 'Reading history' => 'Itan kika', 'Account settings' => 'Eto akọọlẹ', 'Social' => 'Awujọ', 'Private messages' => 'Awọn ifiranṣẹ ikọkọ', 'Reading groups' => 'Awon ẹgbẹ kika', 'Submissions' => 'Awon ifisilẹ', 'My Yuejing' => 'Yuejing mi', 'Hello, ' => 'Pẹlẹ o, ', 'Welcome back.' => 'A ku abo pada.', 'Discover stories' => 'Ṣawari awon itan', 'Reading works' => 'Awon ise ti mo n ka', 'Favorite works' => 'Awon ise ayanfẹ', 'Submitted works' => 'Awon ise ti a fi silẹ', 'Continue reading' => 'Tẹsiwaju kika', 'View all' => 'Wo gbogbo rẹ', 'Continue' => 'Tẹsiwaju', 'Work unavailable' => 'Ise ko si', 'Browse library' => 'Wo ibi ikawe', 'No reading history yet' => 'Ko si itan kika sibẹ', 'Open' => 'Ṣii', 'Communication' => 'Ibaraẹnisọrọ', 'Stay connected with readers and fellow writers' => 'Jẹ ki asopọ wa pelu awon oluka ati onkowe ẹlẹgbẹ', 'Start or continue a direct conversation' => 'Bẹrẹ tabi tẹsiwaju ibaraẹnisọrọ taara', 'Open messages' => 'Ṣii ifiranṣẹ', 'Join or create a reading group' => 'Darapo mo tabi ṣẹda ẹgbẹ kika', 'Open groups' => 'Ṣii awọn ẹgbẹ', 'Pending review' => 'N duro de atunyẹwo', 'Approved' => 'Ti fọwọsi', 'Needs changes' => 'O nilo atunṣe',
    'Search users' => 'Wa awon olumulo', 'Search by name or email' => 'Wa nipa orukọ tabi imeeli', 'Loading' => 'N gbe wọle', 'Loading conversations' => 'N gbe awọn ibaraẹnisọrọ wọle', 'Loading groups' => 'N gbe awọn ẹgbẹ wọle', 'DIRECT CHAT' => 'IBARAẸNISỌRỌ TAARA', 'GROUP CHAT' => 'IBARAẸNISỌRỌ ẸGBẸ', 'Choose a conversation' => 'Yan ibaraẹnisọrọ', 'Choose a group' => 'Yan ẹgbẹ', 'Not connected' => 'Ko sopọ', 'Send message' => 'Firanṣẹ', 'Create reading group' => 'Ṣẹda ẹgbẹ kika', 'Group name' => 'Orukọ ẹgbẹ', 'Choose members' => 'Yan awon ọmọ ẹgbẹ', 'Create group' => 'Ṣẹda ẹgbẹ', 'Members' => 'Awon ọmọ ẹgbẹ', 'Add member' => 'Fi ọmọ ẹgbẹ kun', 'Choose member' => 'Yan ọmọ ẹgbẹ',
    'Email' => 'Imeeli', 'Password' => 'Ọrọigbaniwọle', 'Remember me' => 'Ranti mi', 'Forgot password?' => 'O gbagbe ọrọigbaniwọle?', 'Create an account' => 'Ṣẹda akọọlẹ', 'Display name' => 'Orukọ ifihan', 'Account type' => 'Iru akọọlẹ', 'Reader: read, save, and sync progress' => 'Oluka: ka, fipamọ, ki o mu ilọsiwaju baamu', 'Author: read and submit works' => 'Onkowe: ka ki o fi awon ise silẹ', 'Set password' => 'Ṣeto ọrọigbaniwọle', 'Confirm password' => 'Jẹrisi ọrọigbaniwọle', 'Create account' => 'Ṣẹda akọọlẹ', 'Already have an account?' => 'Ṣe o ti ni akọọlẹ tẹlẹ?', 'New password' => 'Ọrọigbaniwọle tuntun', 'Action completed.' => 'Iṣe ti pari.', 'Settings updated.' => 'A ti ṣe imudojuiwọn eto.', 'Saved' => 'Ti fipamọ', 'Save work' => 'Fipamọ iṣẹ', 'Chapters' => 'Awọn ipin', 'Status' => 'Ipo', 'Reader rating' => 'Iwọn awọn oluka', 'Previous' => 'Ti iṣaaju', 'Next' => 'Atẹle', 'Contents' => 'Akoonu', 'Today' => 'Loni', 'Word count' => 'Iye ọrọ', 'Anonymous author' => 'Onkọwe ti a ko mọ', 'Anonymous user' => 'Olumulo ti a ko mọ', 'Untitled work' => 'Iṣẹ ti ko ni akọle', 'No content' => 'Ko si akoonu', 'Draft' => 'Akọpamọ', 'Published' => 'Ti a gbejade', 'Archived' => 'Ti a fi pamọ', 'Rejected' => 'Ti a kọ', 'In review' => 'N ṣe atunyẹwo', 'Chapter' => 'Ipin', 'Work title' => 'Akọle iṣẹ', 'Genre' => 'Iru itan', 'Synopsis' => 'Akopọ itan', 'Content' => 'Akoonu', 'Save changes' => 'Fipamọ awọn ayipada', 'Edit' => 'Ṣatunkọ', 'Delete' => 'Pa', 'Save' => 'Fipamọ', 'Publish' => 'Gbejade', 'All' => 'Gbogbo', 'Pending' => 'N duro', 'Author' => 'Onkowe', 'Time' => 'Akoko', 'Target' => 'Ibi-afẹde', 'Action' => 'Iṣe', 'Operator' => 'Olupese', 'Metadata' => 'Alaye metadata', 'No audit records yet.' => 'Ko si igbasilẹ ayewo sibẹ.',
];
$fallback = 'Akọsilẹ yii wa fun ọ.'; $keep = ['Yuejing', 'API', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', '2FA', 'IP', 'JSON'];
$translate = function ($value) use (&$translate, $map, $fallback, $keep) { if (is_array($value)) { foreach ($value as $key => $item) $value[$key] = $translate($item); return $value; } if (!is_string($value)) return $value; $result = strtr($value, $map); if ($result === $value && preg_match('/[A-Za-z]/', $value) && !in_array($value, $keep, true)) { preg_match_all('/:[A-Za-z_][A-Za-z0-9_]*/', $value, $tokens); $result = $fallback.' '.implode(' ', $tokens[0]); } return $result; }; return $translate($source);
