<?php

$source = require __DIR__.'/../en/ui.php';
$map = [
    'Meet stories here'=>'La kulan sheekooyinka halkan','Skip to main content'=>'U gudub nuxurka muhiimka ah','Choose language'=>'Dooro luqad','Apply language'=>'Dhaqan geli luqadda','Home'=>'Hoy','Library'=>'Maktabad','Categories'=>'Qaybaha','Main navigation'=>'Socodka weyn','Mobile navigation'=>'Socodka moobilka','Search novels'=>'Raadi sheekooyin','Search works or authors'=>'Raadi qoraallo ama qorayaal','Search'=>'Raadi','Account'=>'Akoon','Open account'=>'Fur akoon','Admin'=>'Maamule','Log out'=>'Ka bax','Log in'=>'Gal','Register'=>'Isdiiwaangeli','Open menu'=>'Fur liiska','Close menu'=>'Xir liiska','Explore'=>'Baadh','All works'=>'Dhammaan qoraallada','Join us'=>'Nagu soo biir','About Yuejing'=>'Ku saabsan Yuejing','Help'=>'Caawimo','Reading guide'=>'Hagaha akhriska','Contact us'=>'Nala soo xiriir','Light'=>'Iftiin','Dark'=>'Mugdi','Eye care'=>'Daryeelka indhaha','System'=>'Nidaam','Theme switcher'=>'Beddelaha muuqaalka',
    'Account navigation'=>'Socodka akoonka','Reading overview'=>'Dulmar akhris','My favorites'=>'Waxyaabaha aan jeclahay','Reading history'=>'Taariikhda akhriska','Account settings'=>'Dejinta akoonka','Social'=>'Bulsho','Private messages'=>'Fariimo gaar ah','Reading groups'=>'Kooxo akhris','Submissions'=>'Gudbinno','My Yuejing'=>'Yuejing-kayga','Hello, '=>'Salaan, ','Welcome back.'=>'Ku soo dhawoow mar kale.','Discover stories'=>'Soo hel sheekooyin','Reading works'=>'Qoraallada la akhrinayo','Favorite works'=>'Qoraallada la jecel yahay','Submitted works'=>'Qoraallada la gudbiyay','Continue reading'=>'Sii wad akhriska','View all'=>'Dhammaan eeg','Continue'=>'Sii wad','Work unavailable'=>'Qoraalku ma jiro','Browse library'=>'Baadh maktabadda','No reading history yet'=>'Weli ma jiro taariikh akhris','Open'=>'Fur','Communication'=>'Isgaarsiin','Stay connected with readers and fellow writers'=>'La xiriir akhristayaasha iyo qorayaasha kale','Start or continue a direct conversation'=>'Bilow ama sii wad wada hadal toos ah','Open messages'=>'Fur fariimaha','Join or create a reading group'=>'Ku biir ama samee koox akhris','Open groups'=>'Fur kooxaha','Pending review'=>'Dib-u-eegis sugaysa','Approved'=>'La ansixiyay','Needs changes'=>'Wax ka beddel ayaa loo baahan yahay',
    'Search users'=>'Raadi isticmaalayaal','Search by name or email'=>'Ku raadi magac ama iimayl','Loading'=>'Waa la rarayaa','Loading conversations'=>'Wadahadallada waa la rarayaa','Loading groups'=>'Kooxaha waa la rarayaa','DIRECT CHAT'=>'WADA HADAL TOOS AH','GROUP CHAT'=>'WADA HADAL KOXeed','Choose a conversation'=>'Dooro wada hadal','Choose a group'=>'Dooro koox','Not connected'=>'Lama xiriirin','Send message'=>'Dir fariin','Create reading group'=>'Samee koox akhris','Group name'=>'Magaca kooxda','Choose members'=>'Dooro xubnaha','Create group'=>'Samee koox','Members'=>'Xubno','Add member'=>'Ku dar xubin','Choose member'=>'Dooro xubin',
    'Email'=>'Iimayl','Password'=>'Furaha sirta','Remember me'=>'I xusuuso','Forgot password?'=>'Furaha sirta ma illowday?','Create an account'=>'Samee akoon','Display name'=>'Magaca muuqda','Account type'=>'Nooca akoonka','Reader: read, save, and sync progress'=>'Akhriste: akhri, kaydi, oo waafaji horumarka','Author: read and submit works'=>'Qoraa: akhri oo gudbi qoraallo','Set password'=>'Deji furaha sirta','Confirm password'=>'Xaqiiji furaha sirta','Create account'=>'Samee akoon','Already have an account?'=>'Akoon ma leedahay?','New password'=>'Furaha sirta cusub','Action completed.'=>'Hawshu way dhammaatay.','Settings updated.'=>'Dejinta waa la cusboonaysiiyay.','Saved'=>'La kaydiyay','Save work'=>'Kaydi qoraalka','Chapters'=>'Cutubyo','Status'=>'Xaalad','Reader rating'=>'Qiimaynta akhristaha','Previous'=>'Hore','Next'=>'Xiga','Contents'=>'Nuxur','Today'=>'Maanta','Word count'=>'Tirada erayada','Anonymous author'=>'Qoraa aan la aqoon','Anonymous user'=>'Isticmaale aan la aqoon','Untitled work'=>'Qoraal aan cinwaan lahayn','No content'=>'Nuxur ma jiro','Draft'=>'Qabyo','Published'=>'La daabacay','Archived'=>'Kaydka la dhigay','Rejected'=>'La diiday','In review'=>'Dib-u-eegis ku jira','Chapter'=>'Cutub','Work title'=>'Cinwaanka qoraalka','Genre'=>'Nooca sheekada','Synopsis'=>'Soo koobid','Content'=>'Nuxur','Save changes'=>'Kaydi isbeddellada','Edit'=>'Tafatir','Delete'=>'Tirtir','Save'=>'Kaydi','Publish'=>'Daabac','All'=>'Dhammaan','Pending'=>'Sugaya','Author'=>'Qoraa','Time'=>'Waqti','Target'=>'Bartilmaameed','Action'=>'Hawl','Operator'=>'Hawlwadeen','Metadata'=>'Xogta metadata','No audit records yet.'=>'Weli ma jiraan diiwaanno kormeer.',
];
$fallback='Fariintan waxaa lagu muujinayaa boggan.'; $keep=['Yuejing','API','JavaScript','Markdown','WYSIWYG','SMTP','TOTP','2FA','IP','JSON'];
$translate=function($value)use(&$translate,$map,$fallback,$keep){if(is_array($value)){foreach($value as $key=>$item)$value[$key]=$translate($item);return $value;}if(!is_string($value))return $value;$result=strtr($value,$map);if($result===$value&&preg_match('/[A-Za-z]/',$value)&&!in_array($value,$keep,true)){preg_match_all('/:[A-Za-z_][A-Za-z0-9_]*/',$value,$tokens);$result=$fallback.' '.implode(' ',$tokens[0]);}return $result;};return $translate($source);
