<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = ['Meet stories here' => 'Li vir bi çîrokan re hev bibînin', 'Home' => 'Rûpela sereke', 'Library' => 'Pirtûkxane', 'Categories' => 'Kategorî', 'Search' => 'Lêgerîn', 'Account' => 'Hesab', 'Log in' => 'Têketin', 'Log out' => 'Derketin', 'Register' => 'Tomar bûn', 'Admin' => 'Rêvebirin', 'Explore' => 'Vedîtin', 'All works' => 'Hemû berhem', 'Choose language' => 'Ziman hilbijêre', 'Apply language' => 'Ziman bi kar bîne', 'Light' => 'Ronî', 'Dark' => 'Tarî', 'System' => 'Pergal', 'Social' => 'Beşa civakî', 'Private messages' => 'Peyamên taybet', 'Reading groups' => 'Komên xwendinê', 'Submissions' => 'Pêşkêşî', 'Hello, :name' => 'Silav, :name', 'Welcome back. Keep a little time for reading today.' => 'Bi xêr hatî vegeriyan. Îro ji bo xwendinê hinek demê veqetînin.', 'Search users' => 'Li bikarhêneran bigere', 'Send message' => 'Peyam bişîne', 'Create reading group' => 'Koma xwendinê biafirîne', 'Create group' => 'Kom biafirîne', 'Members' => 'Endam', 'Choose member' => 'Endamek hilbijêre', 'Add member' => 'Endam lê zêde bike', 'Email' => 'E-name', 'Password' => 'Şîfre', 'Remember me' => 'Min bi bîr bîne', 'Forgot password?' => 'Şîfre ji bîr kir?', 'Create an account' => 'Hesab biafirîne', 'Display name' => 'Navê xuya', 'Account type' => 'Cureyê hesabê', 'New password' => 'Şîfreya nû', 'Reset password' => 'Şîfreyê nû bike', 'My favorites' => 'Bijartiyên min', 'Reading history' => 'Dîroka xwendinê', 'Account settings' => 'Mîhengên hesabê', 'Save changes' => 'Guherînan tomar bike', 'Start reading' => 'Xwendinê dest pê bike', 'Continue' => 'Bidomîne', 'Open' => 'Veke', 'Previous' => 'Pêşî', 'Next' => 'Paşê', 'Contents' => 'Naverok', 'Chapter list' => 'Lîsteya beşan', 'Status' => 'Rewş', 'Pending review' => 'Li benda nirxandinê ye', 'Approved' => 'Hat pejirandin', 'Rejected' => 'Hat redkirin', 'Draft' => 'Nivîsa pêşîn', 'Published' => 'Hat weşandin', 'Archived' => 'Hat arşîvkirin', 'Loading' => 'Tê barkirin', 'Read' => 'Hat xwendin', 'Unread' => 'Nehatiye xwendin', 'Me' => 'Ez', 'Other' => 'Yên din', 'No content' => 'Naverok tune ye', 'Anonymous user' => 'Bikarhênerê bênav', 'Anonymous author' => 'Nivîskarê bênav', 'Untitled work' => 'Berhema bêsernav', 'Unknown' => 'Nenas'];
$words = ['works' => 'berhem', 'readers' => 'xwîner', 'story' => 'çîrok', 'stories' => 'çîrok', 'chapter' => 'beş', 'chapters' => 'beş', 'message' => 'peyama', 'messages' => 'peyaman', 'group' => 'kom', 'groups' => 'kom', 'author' => 'nivîskar', 'reader' => 'xwîner', 'user' => 'bikarhêner', 'users' => 'bikarhêner', 'name' => 'nav', 'title' => 'sernav', 'content' => 'naverok', 'save' => 'tomar', 'saved' => 'hat tomarkirin', 'open' => 'vekirin', 'new' => 'nû', 'back' => 'paşve', 'settings' => 'mîheng', 'review' => 'nirxandin', 'send' => 'şandin', 'create' => 'afirandin', 'choose' => 'hilbijartin', 'loading' => 'barkirin', 'empty' => 'vala', 'today' => 'îro', 'recent' => 'dawî', 'email' => 'e-name', 'password' => 'şîfre'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
