<?php

$base = require __DIR__ . '/../en/ui.php';
$phrases = ['Meet stories here' => 'Այստեղ հանդիպեք պատմություններին', 'Home' => 'Գլխավոր էջ', 'Library' => 'Գրադարան', 'Categories' => 'Բաժիններ', 'Search' => 'Որոնել', 'Account' => 'Հաշիվ', 'Log in' => 'Մուտք գործել', 'Log out' => 'Դուրս գալ', 'Register' => 'Գրանցվել', 'Admin' => 'Կառավարում', 'Explore' => 'Բացահայտել', 'All works' => 'Բոլոր ստեղծագործությունները', 'Choose language' => 'Ընտրեք լեզուն', 'Apply language' => 'Կիրառել լեզուն', 'Light' => 'Բաց', 'Dark' => 'Մուգ', 'System' => 'Համակարգային', 'Social' => 'Սոցիալական բաժին', 'Private messages' => 'Անձնական հաղորդագրություններ', 'Reading groups' => 'Ընթերցանության խմբեր', 'Submissions' => 'Ներկայացումներ', 'Hello, :name' => 'Բարև, :name', 'Welcome back. Keep a little time for reading today.' => 'Բարի վերադարձ։ Այսօր մի փոքր ժամանակ հատկացրեք ընթերցանությանը։', 'Search users' => 'Որոնել օգտատերերի', 'Send message' => 'Ուղարկել հաղորդագրություն', 'Create reading group' => 'Ստեղծել ընթերցանության խումբ', 'Create group' => 'Ստեղծել խումբ', 'Members' => 'Անդամներ', 'Choose member' => 'Ընտրեք անդամին', 'Add member' => 'Ավելացնել անդամ', 'Email' => 'Էլեկտրոնային հասցե', 'Password' => 'Գաղտնաբառ', 'Remember me' => 'Հիշել ինձ', 'Forgot password?' => 'Մոռացե՞լ եք գաղտնաբառը', 'Create an account' => 'Ստեղծել հաշիվ', 'Display name' => 'Ցուցադրվող անուն', 'Account type' => 'Հաշվի տեսակ', 'New password' => 'Նոր գաղտնաբառ', 'Reset password' => 'Վերականգնել գաղտնաբառը', 'My favorites' => 'Իմ նախընտրածները', 'Reading history' => 'Ընթերցանության պատմություն', 'Account settings' => 'Հաշվի կարգավորումներ', 'Save changes' => 'Պահպանել փոփոխությունները', 'Start reading' => 'Սկսել ընթերցումը', 'Continue' => 'Շարունակել', 'Open' => 'Բացել', 'Previous' => 'Նախորդ', 'Next' => 'Հաջորդ', 'Contents' => 'Բովանդակություն', 'Chapter list' => 'Գլուխների ցանկ', 'Status' => 'Կարգավիճակ', 'Pending review' => 'Սպասում է ստուգման', 'Approved' => 'Հաստատված', 'Rejected' => 'Մերժված', 'Draft' => 'Սևագիր', 'Published' => 'Հրապարակված', 'Archived' => 'Արխիվացված', 'Loading' => 'Բեռնվում է', 'Read' => 'Կարդացված', 'Unread' => 'Չկարդացված', 'Me' => 'Ես', 'Other' => 'Այլ', 'No content' => 'Բովանդակություն չկա', 'Anonymous user' => 'Անանուն օգտատեր', 'Anonymous author' => 'Անանուն հեղինակ', 'Untitled work' => 'Անվերնագիր ստեղծագործություն', 'Unknown' => 'Անհայտ'];
$words = ['works' => 'ստեղծագործություններ', 'readers' => 'ընթերցողներ', 'story' => 'պատմություն', 'stories' => 'պատմություններ', 'chapter' => 'գլուխ', 'chapters' => 'գլուխներ', 'message' => 'հաղորդագրություն', 'messages' => 'հաղորդագրություններ', 'group' => 'խումբ', 'groups' => 'խմբեր', 'author' => 'հեղինակ', 'reader' => 'ընթերցող', 'user' => 'օգտատեր', 'users' => 'օգտատերեր', 'name' => 'անուն', 'title' => 'վերնագիր', 'content' => 'բովանդակություն', 'save' => 'պահպանել', 'saved' => 'պահպանված', 'open' => 'բացել', 'new' => 'նոր', 'back' => 'հետ', 'settings' => 'կարգավորումներ', 'review' => 'ստուգում', 'send' => 'ուղարկել', 'create' => 'ստեղծել', 'choose' => 'ընտրել', 'loading' => 'բեռնվում է', 'empty' => 'դատարկ', 'today' => 'այսօր', 'recent' => 'վերջին', 'email' => 'էլեկտրոնային հասցե', 'password' => 'գաղտնաբառ'];
$keep = ['Yuejing', 'JavaScript', 'Markdown', 'WYSIWYG', 'SMTP', 'TOTP', 'API', 'JSON'];
$convert = function ($text) use ($phrases, $words, $keep) { if (!is_string($text) || in_array($text, $keep, true)) return $text; $tokens = []; $text = preg_replace_callback('/:([A-Za-z0-9_]+)/', function ($m) use (&$tokens) { $key = '__ZZTOKEN' . count($tokens) . 'ZZ__'; $tokens[$key] = $m[0]; return $key; }, $text); $out = $phrases[$text] ?? strtr($text, $words); if ($out === $text) $out = $text; foreach ($tokens as $key => $token) $out = str_replace($key, $token, $out); return $out; };
$walk = function (&$node) use (&$walk, $convert) { foreach ($node as &$value) { if (is_array($value)) $walk($value); else $value = $convert($value); } };
$walk($base);
return $base;
